### ISSUE TITLE
Auto-completion contains all global symbols

### ISSUE THREAD

**Issue by bjoernpollex** [ipython/ipykernel#299]
In various contexts (e.g. in paths or strings) auto-completions contain a long list of global symbols, which makes it hard to use it to find relevant items. For example (with `ipykernel` 4.8.0):

<img width="430" alt="screen shot 2018-01-18 at 13 05 57" src="https://user-images.githubusercontent.com/1698589/35097459-7c0f8fe0-fc50-11e7-96ec-32e7453a0598.png">

The actual key is somewhere halfway down this very long list. Multiple users have reported this issue in other projects:

 - `ipython`:
    - [Tab completion behaviour changed for file paths][1] *
    - [[Completions] dict key completion occluded by kitchen sink][2]
 - `notebook`:
   - [jupyter notebook is loading incorrect auto completion for file paths][3] *

The ones marked with * have reported that downgrading to `ipykernel` 4.6.1 fixes the issue for them, so I'm reporting it here. For comparison, when I downgrade to 4.6.1, I get this:

<img width="389" alt="screen shot 2018-01-18 at 13 11 30" src="https://user-images.githubusercontent.com/1698589/35097618-2d4c2dd6-fc51-11e7-9bdd-a8d4668af801.png">

However, when I type `''` for a string, the correct value disappears from the list:

<img width="378" alt="screen shot 2018-01-18 at 13 11 44" src="https://user-images.githubusercontent.com/1698589/35097637-48b2050a-fc51-11e7-8258-deb4b9cdfc28.png">

I'm using:

 - Python 3.6.4
 - ipykernel (4.6.1)
 - ipython (6.2.1)
 - jupyter (1.0.0)
 - jupyter-client (5.2.1)
 - jupyter-console (5.2.0)
 - jupyter-core (4.4.0)
 - notebook (5.3.1)

[1]: https://github.com/ipython/ipython/issues/10961
[2]: https://github.com/ipython/ipython/issues/10926
[3]: https://github.com/jupyter/notebook/issues/3164

**Comment by takluyver** [comment]
Check that your jedi is up to date. If it is, then I think an upcoming release of IPython should fix this at least inside strings.

**Comment by bjoernpollex** [comment]
I'm using `jedi` 0.11.1. Installing `ipython` master doesn't fix this issue. I've been looking a little bit at the completer code, but it will take a lot more time to figure out exactly what's going on (especially why downgrading `ipykernel` has fixed the issue for some). One thing that does strike me as odd is that [here][1] all completions are basically sorted alphabetically, regardless or their origin.

[1]: https://github.com/ipython/ipython/blob/ddfa1ba012793927a1380e6d0fdbb5291b850b62/IPython/core/completer.py#L2046

**Comment by bjoernpollex** [comment]
Ok, seems like a `jedi` issue:

<img width="398" alt="screen shot 2018-01-19 at 13 50 39" src="https://user-images.githubusercontent.com/1698589/35151742-ccfd3932-fd1f-11e7-86d0-398cb6d7be34.png">

However, within the quotes it still has the undesirable behavior that the key is way down the list:

<img width="401" alt="screen shot 2018-01-19 at 13 51 46" src="https://user-images.githubusercontent.com/1698589/35151788-fa9421d0-fd1f-11e7-93b1-de72a39c7d5a.png">

Also, in both cases the list seems to contain all the same symbols, just in a different order.

**Comment by takluyver** [comment]
I'm not too surprised by the case outside the quotes - our completion machinery is generally not very clever, so I'd expect to see things like exceptions there. I am a bit surprised by the problem inside the quotes - the code calculating Jedi completions is meant to skip if it is in a string:

https://github.com/ipython/ipython/blob/db2a0da26a0a3f9c6720378a9931db9d2eddaa0b/IPython/core/completer.py#L1376

**Comment by bjoernpollex** [comment]
So, debugging this shows that the check inside the string isn't triggered, because [this][1] type check fails. Apparently the object is of type `PythonErrorNode`, which is not an instance of `ErrorLeaf`.

[1]: https://github.com/ipython/ipython/blob/db2a0da26a0a3f9c6720378a9931db9d2eddaa0b/IPython/core/completer.py#L1372

**Comment by takluyver** [comment]
Check which variant of `ErrorLeaf` it is importing - I had a problem at one point because it was getting the wrong type between parso (used by newer versions of jedi) and an older version of jedi.

**Comment by bjoernpollex** [comment]
So, there's a couple of cases here:

 1. When completing after `d['` the code works as expected.
 2. When completing inside the string of `d[''` it fails because `next_to_last_tree` is a `PythonErrorNode`
 3. When completing inside the string of `d['']` it fails because `next_to_last_tree` is a `PythonNode` - there is no syntax error here.

I'm happy to look into this a bit more - it seems that all the pieces are there, just the logic has some flaws.

**Comment by takluyver** [comment]
Ah, got it. One way to deal with that would be to cut the string off at the cursor, so those three cases are all the same. I thought we already did that, but evidently not. I don't know if Jedi can do any completions smarter if it has the text after the cursor.

**Comment by bjoernpollex** [comment]
Yes, that seems like the way to do it. Since this is clearly an `ipython` issue, I'll close this one and open a new issue there, linking to this one. I'll also try and prepare a pull request.

**Comment by takluyver** [comment]
Thanks :-)
