### ISSUE TITLE
Ipykernel passes broken argument to Tornado in Python3.4

### ISSUE THREAD

**Issue by buckbaskin** [ipython/ipykernel#303]
I am on Ubuntu 14.04, and am using Jupyter Notebook v 5.4.0. I have installed both Python2 and Python3 using apt and both kernels for Jupyter Notebook. I installed jupyter using pip and am up to date from pip's perspective for all packages as of the submission of the issue. Upon opening the notebook to use Python3 kernel, I found that it still uses Python2. In order to fix this, I referenced https://github.com/jupyter/notebook/issues/2563 and changed the kernel.json file in the python3 kernel directory to use python3. This fixed issue I had that included `python2` but did not resolve the following error that I received. This causes the kernel to die permanently in a Python3 notebook. On my machine, this can be reproduced by starting up jupyter notebook in a directory with or without previous notebooks and attempting to open a Python3 kernel-based notebook.

```
Traceback (most recent call last):
  File "/usr/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.4/dist-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/usr/local/lib/python3.4/dist-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-123>", line 2, in initialize
  File "/usr/local/lib/python3.4/dist-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/ipykernel/kernelapp.py", line 448, in initialize
    self.init_sockets()
  File "/usr/local/lib/python3.4/dist-packages/ipykernel/kernelapp.py", line 251, in init_sockets
    self.init_iopub(context)
  File "/usr/local/lib/python3.4/dist-packages/ipykernel/kernelapp.py", line 259, in init_iopub
    self.iopub_thread = IOPubThread(self.iopub_socket, pipe=True)
  File "/usr/local/lib/python3.4/dist-packages/ipykernel/iostream.py", line 66, in __init__
    self.io_loop = IOLoop(make_current=False)
  File "/home/buck/ros_ws/src/rosbridge_suite/rosbridge_server/src/tornado/util.py", line 208, in __new__
    instance.initialize(**args)
  File "/usr/local/lib/python3.4/dist-packages/zmq/eventloop/ioloop.py", line 139, in initialize
    super(ZMQIOLoop, self).initialize(impl=impl, **kwargs)
TypeError: initialize() got an unexpected keyword argument 'make_current'
```

I might be missing something obvious in my installation, but I can't seem to figure out what it is. This error is breaking my ability to run either jupyter notebooks or ipython notebooks.

## Hopefully Helpful Things from the Contributions Guidelines

```
python3 -c "import IPython; print(IPython.sys_info())"
{'commit_hash': 'ca5443062',
 'commit_source': 'installation',
 'default_encoding': 'UTF-8',
 'ipython_path': '/usr/local/lib/python3.4/dist-packages/IPython',
 'ipython_version': '6.2.1',
 'os_name': 'posix',
 'platform': 'Linux-3.13.0-141-generic-x86_64-with-Ubuntu-14.04-trusty',
 'sys_executable': '/usr/bin/python3',
 'sys_platform': 'linux',
 'sys_version': '3.4.3 (default, Nov 28 2017, 16:41:13) \n[GCC 4.8.4]'}
```

### Version Info

```
pip==9.0.1
jupyter==1.0.0
jupyter-client==5.2.2
jupyter-console==5.2.0
jupyter-core==4.4.0
tornado==4.5.3
```

Looking through the code in the `ipykernel/iostream.py` file, it looks like the loop is getting passed an incorrect argument. Perhaps it makes sense to instantiate without the argument and `call clear_current()`? This is based on my reading of the IOLoop documentation. Please let me know if there is other information that would be helpful.

**Comment by minrk** [comment]
what's the version of `ipykernel`? I thought we fixed this in 4.7 or 4.8. Current ipykernel is 4.8.1.

**Comment by buckbaskin** [comment]
pip indicates that I have version 4.8.0. However, in an attempt to run things again, I'm not seeing the same error, but the kernel still doesn't load. I think that it makes sense to close this issue, and I can either reopen it or open a new one when I track down what appears to be a different issue (potentially on my end). Thank you for responding.

**Comment by takluyver** [comment]
OK, thanks. Check that the PYTHONPATH environment variable is not set - that can cause it to find the wrong files.
