### ISSUE TITLE
DeprecationWarning has unclear origin: `should_run_async` will not call `transform_cell` automatically in the future

### ISSUE THREAD

**Issue by courtarro** [ipython/ipykernel#540]
This deprecation appears when I have warnings enabled, as of some time within the past week or so, and it is unclear what its origin is. How would I go about finding what component is causing this warning to appear?

For the record, the following code causes the problem to appear:

```python
import warnings
import pandas as pd
warnings.simplefilter('always')
pd.read_csv('filename.csv')
```

I could turn off warnings, obviously, but I need them for other situations. Hiding the issue doesn't really fix it, of course. I have the standard contrib notebook extensions installed also.

**Comment by Carreau** [comment]
Sorry those are just internal APIs.I transfered this issue to IPykernel repository.

**Comment by hellodanylo** [comment]
Another workaround is to downgrade IPython to 7.10 until this issue is resolved in IPyKernel

**Comment by jckling** [comment]
Same problem here

**Comment by mattpodolak** [comment]
I got this error as well, it seems like if it's triggered once it will print out in ever cell afterward.

It first occurred when printing out values from a list:

```
post_to_comments_list[:10]
```

All the following cells triggered this warning as well, including this cell:

```
tst_arr = [1, 2, 3]
```

**Comment by asford** [comment]
Does this need a owner? Would a fix for this fit in the 6.0 release timeline?

**Comment by Carreau** [comment]
#605 is not a proper fix, it re-introduces the exact bug that was painfully fixed in CLI IPython.

**Comment by Carreau** [comment]
Sorry it does not reintroduce it, the bug is still there in IPykernel ; it just mute the error message.

**Comment by gansanay** [comment]
I am still getting this warning at each cell in jupyterlab. python==3.9.2, ipykernel==5.5.3, ipython==7.21.0.

**Comment by cam4ani** [comment]
me too

**Comment by Carreau** [comment]
Do you have a file and line number for this warning ? it would be helpful to know which lines trigger it.

**Comment by stridera** [comment]
```
.venv/lib/python3.8/site-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)
```

**Comment by gboeing** [comment]
@Carreau this warning is still appearing with ipykernel=5.5.3, ipython=7.22.0, python=3.9.2:

```
miniconda3/envs/ox/lib/python3.9/site-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)
```

**Comment by Carreau** [comment]
> @Carreau this warning is still appearing with ipykernel=5.5.3, ipython=7.22.0, python=3.9.2:

That appear to be expected, the fix in only on the master branch that will become 6.0.

**Comment by gboeing** [comment]
Ah, thanks. I see now the fix is in #617. Looking forward to it in the 6.0 release.

**Comment by vvid643** [comment]
Hi, can anyone help me with installing this commit into my already installed package?

macOS 11.3.1
ipykernel==5.5.5
ipython==7.21.0
Python 3.8.8
